services:
  postgres:
    container_name: postgres_go_v2
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin_avito
      POSTGRES_PASSWORD: no_wb_yes_avito
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5433:5432"